### ISSUE TITLE
Update for latest Colyseus server version?

### ISSUE THREAD

**Issue by cemck** [chunho32/colyseus-cocos2d-x#4]
Hi is this project maintained anymore?

**Comment by endel** [comment]
I'd like to thank @chunho32 for making this initial version. It really helped a lot to make the official client that was released today: https://github.com/colyseus/colyseus-cocos2d-x

If you're interested in using this, please use the new version, and create issues/pull-requests on the official repository!

@chunho32 please let me know if you're still using Colyseus, and if you're interested in helping me to maintain the C++ client 🤗 

Cheers!

**Comment by cemck** [comment]
Thank you! Nice work 👍
